server:
  port: 5555
 
spring:
  application:
    name: api-gateway
  main:
    allow-circular-references: true
 
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
zuul:
  prefix: /api
  routes:
    # 수동 경로 매핑  http://localhost:5555/srve2/v1/~~
    service2: /srve2/**
    
management:
  endpoints:
    web:
      exposure:
        include: "*"